-- MySQL Script generated by MySQL Workbench
-- Thu Jun  3 16:51:35 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema FUME-DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema FUME-DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `FUME-DB` DEFAULT CHARACTER SET utf8 ;
USE `FUME-DB` ;

-- -----------------------------------------------------
-- Table `FUME-DB`.`Kunden`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FUME-DB`.`Kunden` ;

CREATE TABLE IF NOT EXISTS `FUME-DB`.`Kunden` (
  `Kunden-ID` INT NOT NULL,
  `Vorname` VARCHAR(45) NOT NULL,
  `Nachname` VARCHAR(45) NOT NULL,
  `Adresse` VARCHAR(45) NOT NULL,
  `Status` VARCHAR(45) NOT NULL,
  `Beginndatum` DATE NOT NULL,
  `Enddatum` DATE NULL,
  PRIMARY KEY (`Kunden-ID`),
  UNIQUE INDEX `Kunden-ID_UNIQUE` (`Kunden-ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FUME-DB`.`Bikes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FUME-DB`.`Bikes` ;

CREATE TABLE IF NOT EXISTS `FUME-DB`.`Bikes` (
  `Bike-ID` INT NOT NULL,
  `Kunden_Kunden-ID` INT NOT NULL,
  `Fahrradtyp` VARCHAR(45) NOT NULL,
  `Kaufdatum` DATE NOT NULL,
  `GPS` VARCHAR(45) NOT NULL,
  `Standort` VARCHAR(45) NOT NULL,
  `Status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Bike-ID`, `Kunden_Kunden-ID`),
  UNIQUE INDEX `Bike-ID_UNIQUE` (`Bike-ID` ASC) VISIBLE,
  INDEX `fk_Bikes_Kunden_idx` (`Kunden_Kunden-ID` ASC) VISIBLE,
  CONSTRAINT `fk_Bikes_Kunden`
    FOREIGN KEY (`Kunden_Kunden-ID`)
    REFERENCES `FUME-DB`.`Kunden` (`Kunden-ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FUME-DB`.`Services`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FUME-DB`.`Services` ;

CREATE TABLE IF NOT EXISTS `FUME-DB`.`Services` (
  `Service-ID` INT NOT NULL,
  `Serviceart` VARCHAR(45) NULL,
  PRIMARY KEY (`Service-ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FUME-DB`.`Bikes_has_Services`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FUME-DB`.`Bikes_has_Services` ;

CREATE TABLE IF NOT EXISTS `FUME-DB`.`Bikes_has_Services` (
  `Bikes_Bike-ID` INT NOT NULL,
  `Bikes_Kunden_Kunden-ID` INT NOT NULL,
  `Services_Service-ID` INT NOT NULL,
  `Erstellungsdatum` DATE NOT NULL,
  `Bearbeitungsdatum` DATE NOT NULL,
  `Mitarbeiter` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Bikes_Bike-ID`, `Bikes_Kunden_Kunden-ID`, `Services_Service-ID`),
  INDEX `fk_Bikes_has_Services_Services1_idx` (`Services_Service-ID` ASC) VISIBLE,
  INDEX `fk_Bikes_has_Services_Bikes1_idx` (`Bikes_Bike-ID` ASC, `Bikes_Kunden_Kunden-ID` ASC) VISIBLE,
  CONSTRAINT `fk_Bikes_has_Services_Bikes1`
    FOREIGN KEY (`Bikes_Bike-ID` , `Bikes_Kunden_Kunden-ID`)
    REFERENCES `FUME-DB`.`Bikes` (`Bike-ID` , `Kunden_Kunden-ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Bikes_has_Services_Services1`
    FOREIGN KEY (`Services_Service-ID`)
    REFERENCES `FUME-DB`.`Services` (`Service-ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;